spring:
  application:
    name:zelda_java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/zelda?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

server:
  port:8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

# 文件上传配置
upload:
  path: /uploads/
